from typing import Protocol

from src.api.schemas import ResearchRecord, ResearchRequest, ResearchStatus, SearchTask, TaskUpdate


class TaskStore(Protocol):
    def add_research(self, request: ResearchRequest, task_ids: list[str]) -> ResearchRecord: ...

    def get_research(self, research_id: str) -> ResearchRecord | None: ...

    def update_research_status(
        self,
        research_id: str,
        status: ResearchStatus,
        report: str | None = None,
    ) -> ResearchRecord | None: ...

    def add_task(self, task_data: dict) -> SearchTask: ...

    def get_task(self, task_id: str) -> SearchTask | None: ...

    def get_all_tasks(self) -> list[SearchTask]: ...

    def get_tasks_by_research(self, research_id: str) -> list[SearchTask]: ...

    def update_task(self, task_id: str, update: TaskUpdate) -> SearchTask | None: ...
