"""Declarative catalog and metadata for all multi-agent search agents."""

from src.domain import AgentMetadataItem

AGENTS_CATALOG: list[AgentMetadataItem] = [
    # ── Stage 1: Planning ─────────────────────────────────────────────────────
    AgentMetadataItem(
        id="clarifier",
        name="ClarifierAgent",
        stage="planning",
        role="Query Clarification & Ambiguity Resolver",
        trigger="Incoming user research request with ambiguous or short prompts",
        llm_model="deepseek-chat",
        inputs=["prompt", "user_context"],
        outputs=["clarification_needed", "suggested_followups"],
        source_file="src/agents/clarifier.py",
        line_number=1,
        description="Detects underspecified or ambiguous prompts, suggesting targeted clarifying questions.",
        dependencies=[],
    ),
    AgentMetadataItem(
        id="optimizer",
        name="PromptOptimizerAgent",
        stage="planning",
        role="Prompt Expansion & Perspective Synthesis",
        trigger="Initial research dispatch",
        llm_model="deepseek-chat",
        inputs=["prompt", "depth", "language"],
        outputs=["optimized_prompt", "angles", "hypotheses"],
        source_file="src/agents/optimizer.py",
        line_number=1,
        description="Enriches user prompts with academic, industry, and multi-angle perspectives.",
        dependencies=["clarifier"],
    ),
    AgentMetadataItem(
        id="orchestrator",
        name="OrchestratorAgent",
        stage="planning",
        role="Task Decomposition & Execution Planning",
        trigger="Post prompt optimization",
        llm_model="deepseek-chat",
        inputs=["optimized_prompt", "depth"],
        outputs=["subtasks", "queries", "execution_graph"],
        source_file="src/agents/orchestrator.py",
        line_number=1,
        description="Decomposes research goal into structured search tasks with specific search queries.",
        dependencies=["optimizer"],
    ),
    AgentMetadataItem(
        id="cross_language",
        name="CrossLanguageAgent",
        stage="planning",
        role="Multilingual Query Expansion",
        trigger="Orchestrator planning pass if cross_language_enabled",
        llm_model="deepseek-chat",
        inputs=["queries", "target_languages"],
        outputs=["translated_queries", "language_specific_subtasks"],
        source_file="src/agents/cross_language.py",
        line_number=1,
        description="Generates native-language search queries in non-query languages (Russian, Chinese, German, etc.) to tap regional sources.",
        dependencies=["orchestrator"],
    ),

    # ── Stage 2: Search & Extraction ──────────────────────────────────────────
    AgentMetadataItem(
        id="search",
        name="SearchAgent",
        stage="search",
        role="Web Search & Native Content Extraction",
        trigger="Worker picks up search_task_job",
        llm_model=None,
        inputs=["query", "depth", "backend"],
        outputs=["raw_snippets", "scraped_pages", "extracted_text"],
        source_file="src/agents/search.py",
        line_number=1,
        description="Executes parallel web searches against DuckDuckGo/SearXNG/Tavily with Rust-accelerated scraping.",
        dependencies=["orchestrator", "cross_language"],
    ),
    AgentMetadataItem(
        id="source_critic",
        name="SourceCriticAgent",
        stage="search",
        role="Low-Value Domain & SEO Spam Gatekeeper",
        trigger="Search result parsing",
        llm_model=None,
        inputs=["search_results", "urls"],
        outputs=["filtered_results", "rejection_reasons"],
        source_file="src/agents/source_critic.py",
        line_number=1,
        description="Rejects clickbait, content farms, parked domains, and scraper sites.",
        dependencies=["search"],
    ),
    AgentMetadataItem(
        id="source_reputation",
        name="SourceReputationAgent",
        stage="search",
        role="Authority & Reliability Scorer",
        trigger="Post source-critic candidate evaluation",
        llm_model=None,
        inputs=["domain", "url", "tls_info"],
        outputs=["reputation_score", "authority_tier", "is_academic"],
        source_file="src/agents/source_reputation.py",
        line_number=1,
        description="Assigns trust weights to scientific repositories (.edu/.gov, PubMed, IEEE) and vetted news outlets.",
        dependencies=["source_critic"],
    ),
    AgentMetadataItem(
        id="source_independence",
        name="SourceIndependenceAgent",
        stage="search",
        role="Syndication & Source Clustering",
        trigger="Result aggregation across subtasks",
        llm_model=None,
        inputs=["all_sources", "text_signatures"],
        outputs=["independent_clusters", "canonical_sources"],
        source_file="src/agents/source_independence.py",
        line_number=1,
        description="Deduplicates syndicated press releases (e.g. AP/Reuters re-publishers) to prevent false consensus.",
        dependencies=["source_reputation"],
    ),
    AgentMetadataItem(
        id="evidence_mapper",
        name="EvidenceMapperAgent",
        stage="search",
        role="Evidence Chunking & Subtask Attribution",
        trigger="End of search stage",
        llm_model=None,
        inputs=["extracted_text", "subtasks"],
        outputs=["attributed_evidence_blocks", "coverage_matrix"],
        source_file="src/agents/evidence_mapper.py",
        line_number=1,
        description="Aligns extracted text paragraphs with specific subtask goals and hypotheses.",
        dependencies=["source_independence"],
    ),

    # ── Stage 3: Synthesis & Verification (LangGraph) ────────────────────────
    AgentMetadataItem(
        id="replan",
        name="ReplanAgent",
        stage="synthesis",
        role="Evidence Gap Analysis & Dynamic Re-Querying",
        trigger="LangGraph conditional edge on evidence evaluation",
        llm_model="deepseek-chat",
        inputs=["subtasks", "evidence_blocks", "gap_threshold"],
        outputs=["gap_detected", "new_search_queries"],
        source_file="src/agents/replan.py",
        line_number=1,
        description="Detects blind spots or unanswered subtasks; spawns targeted secondary search passes if needed.",
        dependencies=["evidence_mapper"],
    ),
    AgentMetadataItem(
        id="analyzer",
        name="AnalyzerAgent",
        stage="synthesis",
        role="Deep Multi-Perspective Synthesis",
        trigger="Finalize graph execution",
        llm_model="deepseek-reasoner",
        inputs=["attributed_evidence_blocks", "prompt", "depth"],
        outputs=["draft_report", "reasoning_steps", "key_findings"],
        source_file="src/agents/analyzer.py",
        line_number=1,
        description="Core reasoning engine synthesizing hundreds of citations into a coherent, structured report.",
        dependencies=["replan"],
    ),
    AgentMetadataItem(
        id="numeric_check",
        name="NumericCheckAgent",
        stage="synthesis",
        role="Statistical & Quantitative Cross-Verification",
        trigger="Draft report generation",
        llm_model=None,
        inputs=["draft_report", "evidence_tables"],
        outputs=["numeric_discrepancies", "reconciled_metrics"],
        source_file="src/agents/numeric_check.py",
        line_number=1,
        description="Validates financial figures, percentages, dates, and units across multilingual sources.",
        dependencies=["analyzer"],
    ),
    AgentMetadataItem(
        id="claim_verifier",
        name="ClaimVerifierAgent",
        stage="synthesis",
        role="Fact-Checking & Hallucination Elimination",
        trigger="Post numerical validation",
        llm_model="deepseek-chat",
        inputs=["key_claims", "primary_sources"],
        outputs=["verified_claims", "unsupported_claims_flagged"],
        source_file="src/agents/claim_verifier.py",
        line_number=1,
        description="Verifies every factual assertion against primary cited sentences to eliminate hallucinations.",
        dependencies=["numeric_check"],
    ),
    AgentMetadataItem(
        id="citation_audit",
        name="CitationAuditAgent",
        stage="synthesis",
        role="Inline Citation Audit & URL Integrity",
        trigger="Verification stage",
        llm_model=None,
        inputs=["draft_report", "cited_urls"],
        outputs=["valid_citations", "broken_or_misleading_citations"],
        source_file="src/agents/citation_audit.py",
        line_number=1,
        description="Audits bracketed citations [1], [2] to ensure the linked page text literally contains the quoted claim.",
        dependencies=["claim_verifier"],
    ),
    AgentMetadataItem(
        id="retraction",
        name="RetractionAgent",
        stage="synthesis",
        role="Academic Retraction Watchdog",
        trigger="Citation audit step if retraction_check_enabled",
        llm_model=None,
        inputs=["dois", "academic_urls"],
        outputs=["retracted_sources", "disclaimer_notices"],
        source_file="src/agents/retraction.py",
        line_number=1,
        description="Queries Crossref and Retraction Watch databases to flag retracted studies.",
        dependencies=["citation_audit"],
    ),
    AgentMetadataItem(
        id="red_team",
        name="RedTeamAgent",
        stage="synthesis",
        role="Adversarial Stress Testing & Counter-Arguments",
        trigger="HARD / deep research depth",
        llm_model="deepseek-chat",
        inputs=["draft_report", "main_thesis"],
        outputs=["counter_arguments", "stress_test_critique"],
        source_file="src/agents/red_team.py",
        line_number=1,
        description="Attacks the draft report's assumptions with devil's advocate arguments to identify cognitive biases.",
        dependencies=["claim_verifier"],
    ),
    AgentMetadataItem(
        id="stance",
        name="StanceAgent",
        stage="synthesis",
        role="Consensus & Divergent Viewpoint Taxonomy",
        trigger="Controversial or multi-faceted topic synthesis",
        llm_model="deepseek-chat",
        inputs=["evidence_blocks", "source_stances"],
        outputs=["consensus_level", "minority_perspectives", "conflicts"],
        source_file="src/agents/stance.py",
        line_number=1,
        description="Categorizes findings into consensus, disputed areas, and emerging minority views.",
        dependencies=["red_team"],
    ),
    AgentMetadataItem(
        id="report_critic",
        name="ReportCriticAgent",
        stage="synthesis",
        role="Editorial Polish, Tone & Brevity Refinement",
        trigger="Final editorial pass if report_editor_enabled",
        llm_model="deepseek-chat",
        inputs=["draft_report", "style_guide"],
        outputs=["polished_report", "executive_summary"],
        source_file="src/agents/report_critic.py",
        line_number=1,
        description="Streamlines prose, applies inverted-pyramid structure, and eliminates redundant filler.",
        dependencies=["stance", "retraction"],
    ),
    AgentMetadataItem(
        id="confidence",
        name="ConfidenceAgent",
        stage="synthesis",
        role="Calibrated Confidence Scoring & Risk Matrix",
        trigger="Pre-finalization",
        llm_model=None,
        inputs=["source_scores", "verification_results", "stance_diversity"],
        outputs=["confidence_score", "trust_indicators", "audit_report"],
        source_file="src/agents/confidence.py",
        line_number=1,
        description="Computes deterministic confidence score (0-100%) and Trust & Transparency audit badge.",
        dependencies=["report_critic"],
    ),

    # ── Stage 4: Delivery & Follow-Up ─────────────────────────────────────────
    AgentMetadataItem(
        id="chat",
        name="ChatAgent",
        stage="delivery",
        role="Interactive Follow-Up Q&A & Deep-Dive Assistant",
        trigger="User chat message on finalized research",
        llm_model="deepseek-chat",
        inputs=["final_report", "evidence_cache", "user_question"],
        outputs=["grounded_response", "referenced_citations"],
        source_file="src/agents/chat.py",
        line_number=1,
        description="Answers interactive user questions grounded strictly in the report's gathered evidence pool.",
        dependencies=["confidence"],
    ),
]


def get_agents_catalog() -> list[AgentMetadataItem]:
    """Return the complete metadata catalog for all multi-agent search agents."""
    return AGENTS_CATALOG
